version: "2.1"

services:

  zeo:
    volumes:
      - ./plone-data:/data

  plone:
    volumes:
      - ./src:/plone/instance/src
      - ./backend/site.cfg:/plone/instance/site.cfg

  frontend:
    volumes:
      - ./frontend:/opt/frontend
